### ISSUE TITLE
typec无法驱动

### ISSUE THREAD

**Issue by kesry** [Lemon1151/rk33xx-armbian#1]
# 原DTB反编译 关于USB设置
usb0 {
		compatible = "rockchip,rk3399-dwc3";
		clocks = <0x08 0x81 0x08 0x83 0x08 0xf6 0x08 0xf9>;
		clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk";
		power-domains = <0x16 0x18>;
		resets = <0x08 0x125>;
		reset-names = "usb3-otg";
		#address-cells = <0x02>;
		#size-cells = <0x02>;
		ranges;
		status = "okay";
		extcon = <0x29>;
		phandle = <0xe6>;

		dwc3@fe800000 {
			compatible = "snps,dwc3";
			reg = <0x00 0xfe800000 0x00 0x100000>;
			interrupts = <0x00 0x69 0x04 0x00>;
			dr_mode = "otg";
			phys = <0x2a 0x2b>;
			phy-names = "usb2-phy\0usb3-phy";
			phy_type = "utmi_wide";
			snps,dis_enblslpm_quirk;
			snps,dis-u2-freeclk-exists-quirk;
			snps,dis_u2_susphy_quirk;
			snps,dis-del-phy-power-chg-quirk;
			snps,tx-ipgap-linecheck-dis-quirk;
			snps,xhci-slow-suspend-quirk;
			snps,xhci-trb-ent-quirk;
			snps,usb3-warm-reset-on-resume-quirk;
			status = "okay";
			phandle = <0xe7>;
		};
	};

	usb1 {
		compatible = "rockchip,rk3399-dwc3";
		clocks = <0x08 0x82 0x08 0x84 0x08 0xf7 0x08 0xf9>;
		clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk";
		power-domains = <0x16 0x18>;
		resets = <0x08 0x126>;
		reset-names = "usb3-otg";
		#address-cells = <0x02>;
		#size-cells = <0x02>;
		ranges;
		status = "okay";
		phandle = <0xe8>;

		dwc3@fe900000 {
			compatible = "snps,dwc3";
			reg = <0x00 0xfe900000 0x00 0x100000>;
			interrupts = <0x00 0x6e 0x04 0x00>;
			dr_mode = "host";
			phys = <0x2c 0x2d>;
			phy-names = "usb2-phy\0usb3-phy";
			phy_type = "utmi_wide";
			snps,dis_enblslpm_quirk;
			snps,dis-u2-freeclk-exists-quirk;
			snps,dis_u2_susphy_quirk;
			snps,dis-del-phy-power-chg-quirk;
			snps,tx-ipgap-linecheck-dis-quirk;
			snps,xhci-slow-suspend-quirk;
			snps,xhci-trb-ent-quirk;
			snps,usb3-warm-reset-on-resume-quirk;
			status = "okay";
			phandle = <0xe9>;
		};
	};

刷入fine3399的armian包，开机正常进系统，网卡正常驱动，typec用不了。

原dtb反编译链接
https://github.com/kesry/rk3399_nvme/blob/main/rk3399-nvme-%E5%8F%8D%E7%BC%96%E8%AF%91.dts

**Comment by Lemon1151** [comment]
> # 原DTB反编译 关于USB设置
> usb0 { compatible = "rockchip,rk3399-dwc3"; clocks = <0x08 0x81 0x08 0x83 0x08 0xf6 0x08 0xf9>; clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk"; power-domains = <0x16 0x18>; resets = <0x08 0x125>; reset-names = "usb3-otg"; #address-cells = <0x02>; #size-cells = <0x02>; ranges; status = "okay"; extcon = <0x29>; phandle = <0xe6>;
> 
> ```
> 	dwc3@fe800000 {
> 		compatible = "snps,dwc3";
> 		reg = <0x00 0xfe800000 0x00 0x100000>;
> 		interrupts = <0x00 0x69 0x04 0x00>;
> 		dr_mode = "otg";
> 		phys = <0x2a 0x2b>;
> 		phy-names = "usb2-phy\0usb3-phy";
> 		phy_type = "utmi_wide";
> 		snps,dis_enblslpm_quirk;
> 		snps,dis-u2-freeclk-exists-quirk;
> 		snps,dis_u2_susphy_quirk;
> 		snps,dis-del-phy-power-chg-quirk;
> 		snps,tx-ipgap-linecheck-dis-quirk;
> 		snps,xhci-slow-suspend-quirk;
> 		snps,xhci-trb-ent-quirk;
> 		snps,usb3-warm-reset-on-resume-quirk;
> 		status = "okay";
> 		phandle = <0xe7>;
> 	};
> };
> 
> usb1 {
> 	compatible = "rockchip,rk3399-dwc3";
> 	clocks = <0x08 0x82 0x08 0x84 0x08 0xf7 0x08 0xf9>;
> 	clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk";
> 	power-domains = <0x16 0x18>;
> 	resets = <0x08 0x126>;
> 	reset-names = "usb3-otg";
> 	#address-cells = <0x02>;
> 	#size-cells = <0x02>;
> 	ranges;
> 	status = "okay";
> 	phandle = <0xe8>;
> 
> 	dwc3@fe900000 {
> 		compatible = "snps,dwc3";
> 		reg = <0x00 0xfe900000 0x00 0x100000>;
> 		interrupts = <0x00 0x6e 0x04 0x00>;
> 		dr_mode = "host";
> 		phys = <0x2c 0x2d>;
> 		phy-names = "usb2-phy\0usb3-phy";
> 		phy_type = "utmi_wide";
> 		snps,dis_enblslpm_quirk;
> 		snps,dis-u2-freeclk-exists-quirk;
> 		snps,dis_u2_susphy_quirk;
> 		snps,dis-del-phy-power-chg-quirk;
> 		snps,tx-ipgap-linecheck-dis-quirk;
> 		snps,xhci-slow-suspend-quirk;
> 		snps,xhci-trb-ent-quirk;
> 		snps,usb3-warm-reset-on-resume-quirk;
> 		status = "okay";
> 		phandle = <0xe9>;
> 	};
> };
> ```
> 
> 刷入fine3399的armian包，开机正常进系统，网卡正常驱动，typec用不了。
> 
> 原dtb反编译链接 https://github.com/kesry/rk3399_nvme/blob/main/rk3399-nvme-%E5%8F%8D%E7%BC%96%E8%AF%91.dts
dts里面没有关于Type-C节点的参数，有空尝试加进去看不能用吧

**Comment by kesry** [comment]
> > # 原DTB反编译 关于USB设置
> > usb0 { compatible = "rockchip,rk3399-dwc3"; clocks = <0x08 0x81 0x08 0x83 0x08 0xf6 0x08 0xf9>; clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk"; power-domains = <0x16 0x18>; resets = <0x08 0x125>; reset-names = "usb3-otg"; #address-cells = <0x02>; #size-cells = <0x02>; ranges; status = "okay"; extcon = <0x29>; phandle = <0xe6>;
> > ```
> > 	dwc3@fe800000 {
> > 		compatible = "snps,dwc3";
> > 		reg = <0x00 0xfe800000 0x00 0x100000>;
> > 		interrupts = <0x00 0x69 0x04 0x00>;
> > 		dr_mode = "otg";
> > 		phys = <0x2a 0x2b>;
> > 		phy-names = "usb2-phy\0usb3-phy";
> > 		phy_type = "utmi_wide";
> > 		snps,dis_enblslpm_quirk;
> > 		snps,dis-u2-freeclk-exists-quirk;
> > 		snps,dis_u2_susphy_quirk;
> > 		snps,dis-del-phy-power-chg-quirk;
> > 		snps,tx-ipgap-linecheck-dis-quirk;
> > 		snps,xhci-slow-suspend-quirk;
> > 		snps,xhci-trb-ent-quirk;
> > 		snps,usb3-warm-reset-on-resume-quirk;
> > 		status = "okay";
> > 		phandle = <0xe7>;
> > 	};
> > };
> > 
> > usb1 {
> > 	compatible = "rockchip,rk3399-dwc3";
> > 	clocks = <0x08 0x82 0x08 0x84 0x08 0xf7 0x08 0xf9>;
> > 	clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk";
> > 	power-domains = <0x16 0x18>;
> > 	resets = <0x08 0x126>;
> > 	reset-names = "usb3-otg";
> > 	#address-cells = <0x02>;
> > 	#size-cells = <0x02>;
> > 	ranges;
> > 	status = "okay";
> > 	phandle = <0xe8>;
> > 
> > 	dwc3@fe900000 {
> > 		compatible = "snps,dwc3";
> > 		reg = <0x00 0xfe900000 0x00 0x100000>;
> > 		interrupts = <0x00 0x6e 0x04 0x00>;
> > 		dr_mode = "host";
> > 		phys = <0x2c 0x2d>;
> > 		phy-names = "usb2-phy\0usb3-phy";
> > 		phy_type = "utmi_wide";
> > 		snps,dis_enblslpm_quirk;
> > 		snps,dis-u2-freeclk-exists-quirk;
> > 		snps,dis_u2_susphy_quirk;
> > 		snps,dis-del-phy-power-chg-quirk;
> > 		snps,tx-ipgap-linecheck-dis-quirk;
> > 		snps,xhci-slow-suspend-quirk;
> > 		snps,xhci-trb-ent-quirk;
> > 		snps,usb3-warm-reset-on-resume-quirk;
> > 		status = "okay";
> > 		phandle = <0xe9>;
> > 	};
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 刷入fine3399的armian包，开机正常进系统，网卡正常驱动，typec用不了。
> > 原dtb反编译链接 https://github.com/kesry/rk3399_nvme/blob/main/rk3399-nvme-%E5%8F%8D%E7%BC%96%E8%AF%91.dts
> > dts里面没有关于Type-C节点的参数，有空尝试加进去看不能用吧

原系统能用typec的，
phy@ff7c0000 {
		compatible = "rockchip,rk3399-typec-phy";
		reg = <0x00 0xff7c0000 0x00 0x40000>;
		#phy-cells = <0x01>;
		clocks = <0x08 0x7e 0x08 0x7d>;
		clock-names = "tcpdcore\0tcpdphy-ref";
		assigned-clocks = <0x08 0x7e>;
		assigned-clock-rates = <0x2faf080>;
		power-domains = <0x16 0x08>;
		resets = <0x08 0x95 0x08 0x94 0x08 0x14c>;
		reset-names = "uphy\0uphy-pipe\0uphy-tcphy";
		rockchip,grf = <0x17>;
		rockchip,typec-conn-dir = <0xe580 0x00 0x10>;
		rockchip,usb3tousb2-en = <0xe580 0x03 0x13>;
		rockchip,usb3-host-disable = <0x2434 0x00 0x10>;
		rockchip,usb3-host-port = <0x2434 0x0c 0x1c>;
		rockchip,external-psm = <0xe588 0x0e 0x1e>;
		rockchip,pipe-status = <0xe5c0 0x00 0x00>;
		rockchip,uphy-dp-sel = <0x6268 0x13 0x13>;
		status = "okay";
		extcon = <0x29>;
		phandle = <0x122>;

		dp-port {
			#phy-cells = <0x00>;
			phandle = <0x2e>;
		};

		usb3-port {
			#phy-cells = <0x00>;
			phandle = <0x2b>;
		};
	};

	phy@ff800000 {
		compatible = "rockchip,rk3399-typec-phy";
		reg = <0x00 0xff800000 0x00 0x40000>;
		#phy-cells = <0x01>;
		clocks = <0x08 0x80 0x08 0x7f>;
		clock-names = "tcpdcore\0tcpdphy-ref";
		assigned-clocks = <0x08 0x80>;
		assigned-clock-rates = <0x2faf080>;
		power-domains = <0x16 0x09>;
		resets = <0x08 0x9d 0x08 0x9c 0x08 0x14d>;
		reset-names = "uphy\0uphy-pipe\0uphy-tcphy";
		rockchip,grf = <0x17>;
		rockchip,typec-conn-dir = <0xe58c 0x00 0x10>;
		rockchip,usb3tousb2-en = <0xe58c 0x03 0x13>;
		rockchip,usb3-host-disable = <0x2444 0x00 0x10>;
		rockchip,usb3-host-port = <0x2444 0x0c 0x1c>;
		rockchip,external-psm = <0xe594 0x0e 0x1e>;
		rockchip,pipe-status = <0xe5c0 0x10 0x10>;
		rockchip,uphy-dp-sel = <0x6268 0x03 0x13>;
		status = "okay";
		phandle = <0x123>;

		dp-port {
			#phy-cells = <0x00>;
			phandle = <0x124>;
		};

		usb3-port {
			#phy-cells = <0x00>;
			phandle = <0x2d>;
		};
	};
这是反编译出来的typec的定义

**Comment by Lemon1151** [comment]
> > > # 原DTB反编译 关于USB设置
> > > usb0 { compatible = "rockchip,rk3399-dwc3"; clocks = <0x08 0x81 0x08 0x83 0x08 0xf6 0x08 0xf9>; clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk"; power-domains = <0x16 0x18>; resets = <0x08 0x125>; reset-names = "usb3-otg"; #address-cells = <0x02>; #size-cells = <0x02>; ranges; status = "okay"; extcon = <0x29>; phandle = <0xe6>;
> > > ```
> > > 	dwc3@fe800000 {
> > > 		compatible = "snps,dwc3";
> > > 		reg = <0x00 0xfe800000 0x00 0x100000>;
> > > 		interrupts = <0x00 0x69 0x04 0x00>;
> > > 		dr_mode = "otg";
> > > 		phys = <0x2a 0x2b>;
> > > 		phy-names = "usb2-phy\0usb3-phy";
> > > 		phy_type = "utmi_wide";
> > > 		snps,dis_enblslpm_quirk;
> > > 		snps,dis-u2-freeclk-exists-quirk;
> > > 		snps,dis_u2_susphy_quirk;
> > > 		snps,dis-del-phy-power-chg-quirk;
> > > 		snps,tx-ipgap-linecheck-dis-quirk;
> > > 		snps,xhci-slow-suspend-quirk;
> > > 		snps,xhci-trb-ent-quirk;
> > > 		snps,usb3-warm-reset-on-resume-quirk;
> > > 		status = "okay";
> > > 		phandle = <0xe7>;
> > > 	};
> > > };
> > > 
> > > usb1 {
> > > 	compatible = "rockchip,rk3399-dwc3";
> > > 	clocks = <0x08 0x82 0x08 0x84 0x08 0xf7 0x08 0xf9>;
> > > 	clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk";
> > > 	power-domains = <0x16 0x18>;
> > > 	resets = <0x08 0x126>;
> > > 	reset-names = "usb3-otg";
> > > 	#address-cells = <0x02>;
> > > 	#size-cells = <0x02>;
> > > 	ranges;
> > > 	status = "okay";
> > > 	phandle = <0xe8>;
> > > 
> > > 	dwc3@fe900000 {
> > > 		compatible = "snps,dwc3";
> > > 		reg = <0x00 0xfe900000 0x00 0x100000>;
> > > 		interrupts = <0x00 0x6e 0x04 0x00>;
> > > 		dr_mode = "host";
> > > 		phys = <0x2c 0x2d>;
> > > 		phy-names = "usb2-phy\0usb3-phy";
> > > 		phy_type = "utmi_wide";
> > > 		snps,dis_enblslpm_quirk;
> > > 		snps,dis-u2-freeclk-exists-quirk;
> > > 		snps,dis_u2_susphy_quirk;
> > > 		snps,dis-del-phy-power-chg-quirk;
> > > 		snps,tx-ipgap-linecheck-dis-quirk;
> > > 		snps,xhci-slow-suspend-quirk;
> > > 		snps,xhci-trb-ent-quirk;
> > > 		snps,usb3-warm-reset-on-resume-quirk;
> > > 		status = "okay";
> > > 		phandle = <0xe9>;
> > > 	};
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 刷入fine3399的armian包，开机正常进系统，网卡正常驱动，typec用不了。
> > > 原dtb反编译链接 https://github.com/kesry/rk3399_nvme/blob/main/rk3399-nvme-%E5%8F%8D%E7%BC%96%E8%AF%91.dts
> > > dts里面没有关于Type-C节点的参数，有空尝试加进去看不能用吧
> 
> 原系统能用typec的， phy@ff7c0000 { compatible = "rockchip,rk3399-typec-phy"; reg = <0x00 0xff7c0000 0x00 0x40000>; #phy-cells = <0x01>; clocks = <0x08 0x7e 0x08 0x7d>; clock-names = "tcpdcore\0tcpdphy-ref"; assigned-clocks = <0x08 0x7e>; assigned-clock-rates = <0x2faf080>; power-domains = <0x16 0x08>; resets = <0x08 0x95 0x08 0x94 0x08 0x14c>; reset-names = "uphy\0uphy-pipe\0uphy-tcphy"; rockchip,grf = <0x17>; rockchip,typec-conn-dir = <0xe580 0x00 0x10>; rockchip,usb3tousb2-en = <0xe580 0x03 0x13>; rockchip,usb3-host-disable = <0x2434 0x00 0x10>; rockchip,usb3-host-port = <0x2434 0x0c 0x1c>; rockchip,external-psm = <0xe588 0x0e 0x1e>; rockchip,pipe-status = <0xe5c0 0x00 0x00>; rockchip,uphy-dp-sel = <0x6268 0x13 0x13>; status = "okay"; extcon = <0x29>; phandle = <0x122>;
> 
> ```
> 	dp-port {
> 		#phy-cells = <0x00>;
> 		phandle = <0x2e>;
> 	};
> 
> 	usb3-port {
> 		#phy-cells = <0x00>;
> 		phandle = <0x2b>;
> 	};
> };
> 
> phy@ff800000 {
> 	compatible = "rockchip,rk3399-typec-phy";
> 	reg = <0x00 0xff800000 0x00 0x40000>;
> 	#phy-cells = <0x01>;
> 	clocks = <0x08 0x80 0x08 0x7f>;
> 	clock-names = "tcpdcore\0tcpdphy-ref";
> 	assigned-clocks = <0x08 0x80>;
> 	assigned-clock-rates = <0x2faf080>;
> 	power-domains = <0x16 0x09>;
> 	resets = <0x08 0x9d 0x08 0x9c 0x08 0x14d>;
> 	reset-names = "uphy\0uphy-pipe\0uphy-tcphy";
> 	rockchip,grf = <0x17>;
> 	rockchip,typec-conn-dir = <0xe58c 0x00 0x10>;
> 	rockchip,usb3tousb2-en = <0xe58c 0x03 0x13>;
> 	rockchip,usb3-host-disable = <0x2444 0x00 0x10>;
> 	rockchip,usb3-host-port = <0x2444 0x0c 0x1c>;
> 	rockchip,external-psm = <0xe594 0x0e 0x1e>;
> 	rockchip,pipe-status = <0xe5c0 0x10 0x10>;
> 	rockchip,uphy-dp-sel = <0x6268 0x03 0x13>;
> 	status = "okay";
> 	phandle = <0x123>;
> 
> 	dp-port {
> 		#phy-cells = <0x00>;
> 		phandle = <0x124>;
> 	};
> 
> 	usb3-port {
> 		#phy-cells = <0x00>;
> 		phandle = <0x2d>;
> 	};
> };
> ```
> 
> 这是反编译出来的typec的定义

你是群里那个吗

**Comment by kesry** [comment]
> > > > # 原DTB反编译 关于USB设置
> > > > usb0 { compatible = "rockchip,rk3399-dwc3"; clocks = <0x08 0x81 0x08 0x83 0x08 0xf6 0x08 0xf9>; clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk"; power-domains = <0x16 0x18>; resets = <0x08 0x125>; reset-names = "usb3-otg"; #address-cells = <0x02>; #size-cells = <0x02>; ranges; status = "okay"; extcon = <0x29>; phandle = <0xe6>;
> > > > ```
> > > > 	dwc3@fe800000 {
> > > > 		compatible = "snps,dwc3";
> > > > 		reg = <0x00 0xfe800000 0x00 0x100000>;
> > > > 		interrupts = <0x00 0x69 0x04 0x00>;
> > > > 		dr_mode = "otg";
> > > > 		phys = <0x2a 0x2b>;
> > > > 		phy-names = "usb2-phy\0usb3-phy";
> > > > 		phy_type = "utmi_wide";
> > > > 		snps,dis_enblslpm_quirk;
> > > > 		snps,dis-u2-freeclk-exists-quirk;
> > > > 		snps,dis_u2_susphy_quirk;
> > > > 		snps,dis-del-phy-power-chg-quirk;
> > > > 		snps,tx-ipgap-linecheck-dis-quirk;
> > > > 		snps,xhci-slow-suspend-quirk;
> > > > 		snps,xhci-trb-ent-quirk;
> > > > 		snps,usb3-warm-reset-on-resume-quirk;
> > > > 		status = "okay";
> > > > 		phandle = <0xe7>;
> > > > 	};
> > > > };
> > > > 
> > > > usb1 {
> > > > 	compatible = "rockchip,rk3399-dwc3";
> > > > 	clocks = <0x08 0x82 0x08 0x84 0x08 0xf7 0x08 0xf9>;
> > > > 	clock-names = "ref_clk\0suspend_clk\0bus_clk\0grf_clk";
> > > > 	power-domains = <0x16 0x18>;
> > > > 	resets = <0x08 0x126>;
> > > > 	reset-names = "usb3-otg";
> > > > 	#address-cells = <0x02>;
> > > > 	#size-cells = <0x02>;
> > > > 	ranges;
> > > > 	status = "okay";
> > > > 	phandle = <0xe8>;
> > > > 
> > > > 	dwc3@fe900000 {
> > > > 		compatible = "snps,dwc3";
> > > > 		reg = <0x00 0xfe900000 0x00 0x100000>;
> > > > 		interrupts = <0x00 0x6e 0x04 0x00>;
> > > > 		dr_mode = "host";
> > > > 		phys = <0x2c 0x2d>;
> > > > 		phy-names = "usb2-phy\0usb3-phy";
> > > > 		phy_type = "utmi_wide";
> > > > 		snps,dis_enblslpm_quirk;
> > > > 		snps,dis-u2-freeclk-exists-quirk;
> > > > 		snps,dis_u2_susphy_quirk;
> > > > 		snps,dis-del-phy-power-chg-quirk;
> > > > 		snps,tx-ipgap-linecheck-dis-quirk;
> > > > 		snps,xhci-slow-suspend-quirk;
> > > > 		snps,xhci-trb-ent-quirk;
> > > > 		snps,usb3-warm-reset-on-resume-quirk;
> > > > 		status = "okay";
> > > > 		phandle = <0xe9>;
> > > > 	};
> > > > };
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 刷入fine3399的armian包，开机正常进系统，网卡正常驱动，typec用不了。
> > > > 原dtb反编译链接 https://github.com/kesry/rk3399_nvme/blob/main/rk3399-nvme-%E5%8F%8D%E7%BC%96%E8%AF%91.dts
> > > > dts里面没有关于Type-C节点的参数，有空尝试加进去看不能用吧
> > 
> > 
> > 原系统能用typec的， phy@ff7c0000 { compatible = "rockchip,rk3399-typec-phy"; reg = <0x00 0xff7c0000 0x00 0x40000>; #phy-cells = <0x01>; clocks = <0x08 0x7e 0x08 0x7d>; clock-names = "tcpdcore\0tcpdphy-ref"; assigned-clocks = <0x08 0x7e>; assigned-clock-rates = <0x2faf080>; power-domains = <0x16 0x08>; resets = <0x08 0x95 0x08 0x94 0x08 0x14c>; reset-names = "uphy\0uphy-pipe\0uphy-tcphy"; rockchip,grf = <0x17>; rockchip,typec-conn-dir = <0xe580 0x00 0x10>; rockchip,usb3tousb2-en = <0xe580 0x03 0x13>; rockchip,usb3-host-disable = <0x2434 0x00 0x10>; rockchip,usb3-host-port = <0x2434 0x0c 0x1c>; rockchip,external-psm = <0xe588 0x0e 0x1e>; rockchip,pipe-status = <0xe5c0 0x00 0x00>; rockchip,uphy-dp-sel = <0x6268 0x13 0x13>; status = "okay"; extcon = <0x29>; phandle = <0x122>;
> > ```
> > 	dp-port {
> > 		#phy-cells = <0x00>;
> > 		phandle = <0x2e>;
> > 	};
> > 
> > 	usb3-port {
> > 		#phy-cells = <0x00>;
> > 		phandle = <0x2b>;
> > 	};
> > };
> > 
> > phy@ff800000 {
> > 	compatible = "rockchip,rk3399-typec-phy";
> > 	reg = <0x00 0xff800000 0x00 0x40000>;
> > 	#phy-cells = <0x01>;
> > 	clocks = <0x08 0x80 0x08 0x7f>;
> > 	clock-names = "tcpdcore\0tcpdphy-ref";
> > 	assigned-clocks = <0x08 0x80>;
> > 	assigned-clock-rates = <0x2faf080>;
> > 	power-domains = <0x16 0x09>;
> > 	resets = <0x08 0x9d 0x08 0x9c 0x08 0x14d>;
> > 	reset-names = "uphy\0uphy-pipe\0uphy-tcphy";
> > 	rockchip,grf = <0x17>;
> > 	rockchip,typec-conn-dir = <0xe58c 0x00 0x10>;
> > 	rockchip,usb3tousb2-en = <0xe58c 0x03 0x13>;
> > 	rockchip,usb3-host-disable = <0x2444 0x00 0x10>;
> > 	rockchip,usb3-host-port = <0x2444 0x0c 0x1c>;
> > 	rockchip,external-psm = <0xe594 0x0e 0x1e>;
> > 	rockchip,pipe-status = <0xe5c0 0x10 0x10>;
> > 	rockchip,uphy-dp-sel = <0x6268 0x03 0x13>;
> > 	status = "okay";
> > 	phandle = <0x123>;
> > 
> > 	dp-port {
> > 		#phy-cells = <0x00>;
> > 		phandle = <0x124>;
> > 	};
> > 
> > 	usb3-port {
> > 		#phy-cells = <0x00>;
> > 		phandle = <0x2d>;
> > 	};
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是反编译出来的typec的定义
> 
> 你是群里那个吗

对，昨天在群里问过你了
